require 'open-uri'
require "net/http"
require "uri"
require 'cgi'
require 'json'
require_relative 'ckan/api'
require_relative 'ckan/model'
require_relative 'ckan/group'
require_relative 'ckan/package'
require_relative 'ckan/resource'
require_relative 'ckan/version'
require_relative 'ckan/datastore'
